
#Mac
# INCLUDEPATHS += /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/
# INCLUDEPATHS += /usr/local/Cellar/sdl2/2.0.8/include/
# INCLUDEPATHS += /usr/local/Cellar/freeimage/3.18.0/include/
# INCLUDEPATHS += /usr/local/Cellar/boost/1.68.0/include/

# LIBRARYPATHS += /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/
# LIBRARYPATHS += /usr/local/Cellar/sdl2/2.0.8/lib/
# LIBRARYPATHS += /usr/local/Cellar/freeimage/3.18.0/lib/
# LIBRARYPATHS += /usr/local/Cellar/boost/1.68.0/lib/
